name: pytest

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
      matrix:
        # Note: python 3.12 is covered by code_coverage.yml, which runs pytest with coverage.
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: false
    - name: Update submodules
      run: |
        git submodule update --init --recursive
        git submodule update --remote --merge --recursive
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade setuptools build
        python -m pip install --upgrade pytest
    - name: Build and install tenpy
      run: |
        python -m build .
        python -m pip install .
    - name: Run pytest
      # configuration in pyproject.toml
      run: pytest
